import { Inter } from "next/font/google";
import Head from "next/head"; 
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Кинопоиск",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <Head>
      <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={inter.className}>
        <Header />
          {children}
        <Footer />
        
        </body>
    </html>
  );
}

